import { EquipType, EquipQuality } from './data';
import EquipData from './equipData';
const enemyData = {
    Slime: {
        name: "史莱姆",
        hp: 100,
        minAtk: 1,
        maxAtk: 1,
        def: 1,
        speed: 1,
        hit: 70,
        dodge: 20,
        crt: 10,
        crtDamage: 200,
        exp: 1,
        hpI: 80,
        minAtkI: 4,
        maxAtkI: 5,
        defI: 16,
        expI: 1,
        equips: ["ID1", "ID2", "ID3", "ID4", "ID5", "ID6", "ID7", "ID8", "ID9"]
    },
    Viper: {
        name: "毒蛇",
        hp: 100,
        minAtk: 1,
        maxAtk: 1,
        def: 1,
        speed: 1,
        hit: 99,
        dodge: 20,
        crt: 10,
        crtDamage: 200,
        exp: 1,
        hpI: 80,
        minAtkI: 3,
        maxAtkI: 4,
        defI: 16,
        expI: 1,
        equips: ["ID1", "ID2", "ID3", "ID4", "ID5", "ID6", "ID7", "ID8", "ID9"]
    },
    Wolf: {
        name: "魔狼",
        hp: 100,
        minAtk: 1,
        maxAtk: 1,
        def: 1,
        speed: 1,
        hit: 70,
        dodge: 20,
        crt: 30,
        crtDamage: 250,
        exp: 1,
        hpI: 80,
        minAtkI: 3,
        maxAtkI: 4,
        defI: 16,
        expI: 1,
        equips: ["ID1", "ID2", "ID3", "ID4", "ID5", "ID6", "ID7", "ID8", "ID9"]
    },
    WildBoar: {
        name: "野猪",
        hp: 100,
        minAtk: 2,
        maxAtk: 2,
        def: 1,
        speed: 1,
        hit: 45,
        dodge: 20,
        crt: 10,
        crtDamage: 200,
        exp: 1,
        hpI: 80,
        minAtkI: 5,
        maxAtkI: 6,
        defI: 16,
        expI: 1,
        equips: ["ID1", "ID2", "ID3", "ID4", "ID5", "ID6", "ID7", "ID8", "ID9"]
    },
    Gargoyle: {
        name: "石像鬼",
        hp: 100,
        minAtk: 1,
        maxAtk: 1,
        def: 1,
        speed: 1,
        hit: 70,
        dodge: 20,
        crt: 10,
        crtDamage: 200,
        exp: 1,
        hpI: 100,
        minAtkI: 2,
        maxAtkI: 3,
        defI: 20,
        expI: 1,
        equips: ["ID1", "ID2", "ID3", "ID4", "ID5", "ID6", "ID7", "ID8", "ID9"]
    }
}
export default enemyData;